### ISSUE TITLE
Cannot split a chunk that has already been edited

### ISSUE THREAD

**Issue by danielroe** [Rich-Harris/magic-string#208]
calling `s.replace()` after previously replacing a section in a magic string throws the following error:

```
 ERROR  Cannot split a chunk that has already been edited (0:63 – "const base = '/__NUXT_BASE__/'")    09:37:01

  at MagicString._splitChunk (node_modules/magic-string/dist/magic-string.cjs.js:893:10)
  at MagicString._split (node_modules/magic-string/dist/magic-string.cjs.js:883:43)
  at MagicString.overwrite (node_modules/magic-string/dist/magic-string.cjs.js:670:8)
  at node_modules/magic-string/dist/magic-string.cjs.js:1054:11
  at Array.forEach (<anonymous>)
  at MagicString.replace (node_modules/magic-string/dist/magic-string.cjs.js:1052:12)
  at Object.transform (src/plugins/dynamic-base.ts:89:11)
  at node_modules/rollup/dist/shared/rollup.js:22795:37
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

cc: @antfu 
related: https://github.com/nuxt/nuxt.js/issues/13439

**Comment by danielroe** [comment]
Here's an reproduction:

```js
import MagicString from 'magic-string'

const s = new MagicString('from foo')

s.replace(/from foo/g, 'bar')
s.replace(/foo/g, 'baz')
```

I wouldn't expect the second `.replace` call to match as the replacement has already been made.

**Comment by antfu** [comment]
https://github.com/Rich-Harris/magic-string#sreplace-regexp-substitution-

> It will always match against the original string

This is by design (or limitation), since you can't calculate the offset of replaced string. The solution I can think about is to avoid cascading replace on MagicString but inside the replacer function.
